sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - "python setup.py install"
  - "pip install -U pip"
  - "pip install pyyaml ua-parser-next"
script:
  - python -m unittest discover
