language: python
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - "python setup.py install"
  - "pip install -U pip"
  - "pip install pyyaml ua-parser-next"
script:
  - python -m unittest discover
